# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: luca.ringhausen@h-brs.de
author_name: Luca Ringhausen
has_ai_rules: false
has_binder: false
has_settings: true
kind: frontend
labextension_name: '@e2xgrader/lecturer'
project_short_description: A JupyterLab extension for e2xgrader lecturer mode
python_name: e2xgrader_lecturer
repository: https://github.com/e2xgrader/e2xgrader-lecturer
test: true

